# Generated by Django 6.0.5 on 2026-05-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='/banners/banner1.jpg', upload_to='banners', verbose_name='图片')),
                ('order', models.IntegerField(verbose_name='顺序')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name_plural': '轮播图',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('img', models.ImageField(default='notice.jpg', upload_to='notice', verbose_name='公告图片')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '公告表',
            },
        ),
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name_plural': '欢迎页图片'},
        ),
    ]
