# Generated by Django 6.0.5 on 2026-05-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0002_banners_notice_alter_welcome_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='食物名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('calorie', models.IntegerField(verbose_name='热量（千卡）')),
                ('protein', models.IntegerField(verbose_name='蛋白质（克）')),
                ('spiciness', models.IntegerField(default=0, verbose_name='辣度（0-5）')),
                ('rating', models.DecimalField(decimal_places=2, default=4.0, max_digits=3, verbose_name='推荐指数')),
                ('img', models.ImageField(default='/foods/default.jpg', upload_to='foods', verbose_name='食物图片')),
                ('description', models.TextField(verbose_name='描述')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '食物推荐',
            },
        ),
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name_plural': '欢迎表'},
        ),
    ]
