# Generated by Django 6.0.5 on 2026-05-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0003_food_alter_welcome_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='welcome',
            options={'verbose_name_plural': '欢迎页图片'},
        ),
        migrations.RemoveField(
            model_name='food',
            name='calorie',
        ),
        migrations.RemoveField(
            model_name='food',
            name='protein',
        ),
        migrations.AddField(
            model_name='food',
            name='calorie_per_100g',
            field=models.IntegerField(default=0, verbose_name='热量（千卡/100g）'),
        ),
        migrations.AddField(
            model_name='food',
            name='carb_per_100g',
            field=models.IntegerField(default=0, verbose_name='碳水化合物（克/100g）'),
        ),
        migrations.AddField(
            model_name='food',
            name='default_weight',
            field=models.IntegerField(default=200, verbose_name='默认份量（克）'),
        ),
        migrations.AddField(
            model_name='food',
            name='fat_per_100g',
            field=models.IntegerField(default=0, verbose_name='脂肪（克/100g）'),
        ),
        migrations.AddField(
            model_name='food',
            name='oil_calorie',
            field=models.IntegerField(default=0, verbose_name='油热量（千卡）'),
        ),
        migrations.AddField(
            model_name='food',
            name='protein_per_100g',
            field=models.IntegerField(default=0, verbose_name='蛋白质（克/100g）'),
        ),
        migrations.AddField(
            model_name='food',
            name='sauce_calorie',
            field=models.IntegerField(default=0, verbose_name='酱料热量（千卡）'),
        ),
    ]
