# Generated by Django 6.0.5 on 2026-05-22 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0005_bill_userbalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMealRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='用户ID')),
                ('food_id', models.IntegerField(verbose_name='菜品ID')),
                ('food_name', models.CharField(max_length=100, verbose_name='菜品名称')),
                ('food_img', models.CharField(blank=True, max_length=200, verbose_name='菜品图片')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('weight', models.IntegerField(default=200, verbose_name='份量(克)')),
                ('calorie', models.IntegerField(verbose_name='实际摄入热量')),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('snack', '加餐')], default='lunch', max_length=20, verbose_name='餐别')),
                ('eat_date', models.DateField(auto_now_add=True, verbose_name='用餐日期')),
                ('eat_time', models.DateTimeField(auto_now_add=True, verbose_name='用餐时间')),
            ],
            options={
                'verbose_name_plural': '用户用餐记录',
                'ordering': ['-eat_time'],
            },
        ),
    ]
