# Generated by Django 6.0.5 on 2026-05-29 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0006_usermealrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, unique=True, verbose_name='微信openid')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='昵称')),
                ('avatar', models.CharField(blank=True, max_length=500, verbose_name='头像')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='手机号')),
                ('token', models.CharField(blank=True, max_length=100, verbose_name='登录token')),
                ('token_expire', models.DateTimeField(blank=True, null=True, verbose_name='token过期时间')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='最后登录')),
            ],
            options={
                'verbose_name_plural': '用户表',
            },
        ),
    ]
