# Generated by Django 6.0.5 on 2026-05-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0007_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile_completed',
            field=models.BooleanField(default=False, verbose_name='是否完善资料'),
        ),
    ]
