# Generated by Django 6.0.5 on 2026-07-03 00:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0009_user_activity_level_user_age_user_allergies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BindWaitQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=64, unique=True, verbose_name='微信用户')),
                ('card_uid', models.CharField(blank=True, max_length=20, verbose_name='卡号（绑定后回填）')),
                ('qrcode_token', models.CharField(max_length=100, unique=True, verbose_name='二维码token')),
                ('expire_at', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
            ],
            options={
                'verbose_name_plural': '绑定等待队列',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RfidCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='activity_level',
            field=models.CharField(blank=True, max_length=20, verbose_name='活动水平'),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='user',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='过敏信息'),
        ),
        migrations.AlterField(
            model_name='user',
            name='body_fat',
            field=models.IntegerField(blank=True, null=True, verbose_name='体脂率(%)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='diet_goal',
            field=models.CharField(blank=True, max_length=20, verbose_name='饮食目标'),
        ),
        migrations.AlterField(
            model_name='user',
            name='diseases',
            field=models.TextField(blank=True, verbose_name='疾病信息'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='身高(cm)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='体重(kg)'),
        ),
        migrations.CreateModel(
            name='CardTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('bind', '绑定'), ('unbind', '解绑'), ('recharge', '充值'), ('deduct', '消费'), ('refund', '退款')], max_length=20, verbose_name='交易类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易金额')),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易前余额')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易后余额')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='交易时间')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='card_transactions', to='smart.user', verbose_name='操作用户')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='smart.rfidcard', verbose_name='RFID卡')),
            ],
            options={
                'verbose_name_plural': '卡交易记录',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='rfid_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='smart.rfidcard', verbose_name='绑定的RFID卡'),
        ),
        migrations.CreateModel(
            name='CardBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '待绑定'), ('active', '已激活'), ('inactive', '已停用'), ('unbound', '已解绑')], default='pending', max_length=20, verbose_name='绑定状态')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='绑定时的余额')),
                ('bind_time', models.DateTimeField(auto_now_add=True, verbose_name='绑定时间')),
                ('unbind_time', models.DateTimeField(blank=True, null=True, verbose_name='解绑时间')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_bindings', to='smart.user', verbose_name='用户')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bindings', to='smart.rfidcard', verbose_name='RFID卡')),
            ],
            options={
                'verbose_name_plural': '卡绑定记录',
                'ordering': ['-bind_time'],
                'unique_together': {('user', 'card')},
            },
        ),
    ]
