# Generated by Django 6.0.5 on 2026-07-03 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0010_bindwaitqueue_rfidcard_alter_user_activity_level_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_uid', models.CharField(max_length=20, verbose_name='卡号')),
                ('user_id', models.IntegerField(verbose_name='用户ID')),
                ('user_name', models.CharField(max_length=20, verbose_name='用户名')),
                ('balance', models.IntegerField(default=0, verbose_name='余额(分)')),
                ('total_price', models.IntegerField(default=0, verbose_name='消费金额(分)')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='刷卡时间')),
            ],
            options={
                'verbose_name_plural': '刷卡记录',
                'ordering': ['-create_time'],
            },
        ),
    ]
