# Generated by Django 6.0.5 on 2026-07-04 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0011_cardrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrecord',
            name='user_id',
            field=models.IntegerField(default=0, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='cardrecord',
            name='user_name',
            field=models.CharField(default='', max_length=20, verbose_name='用户名'),
        ),
    ]
