# Generated by Django 6.0.5 on 2026-07-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0012_alter_cardrecord_user_id_alter_cardrecord_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermealrecord',
            name='protein',
            field=models.IntegerField(default=0, verbose_name='蛋白质(克)'),
        ),
        migrations.AlterField(
            model_name='cardrecord',
            name='user_id',
            field=models.IntegerField(verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='cardrecord',
            name='user_name',
            field=models.CharField(max_length=20, verbose_name='用户名'),
        ),
    ]
