# Generated by Django 6.0.5 on 2026-07-04 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0013_usermealrecord_protein_alter_cardrecord_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=100, verbose_name='用户openid')),
                ('messages', models.TextField(default='[]', verbose_name='聊天记录JSON')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '聊天记录',
            },
        ),
    ]
