# Generated by Django 6.0.5 on 2026-07-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0014_chathistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_uid', models.CharField(max_length=20)),
                ('cmd_type', models.CharField(default='recharge', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '待执行指令',
            },
        ),
    ]
