# Generated by Django 6.0.5 on 2026-07-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart', '0015_pendingcommand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardrecord',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='cardrecord',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='消费金额'),
        ),
    ]
